books:
    resource: "@CypressTestBundle/Controller/BooksController.php"
    type:     rest
    prefix:   /api
    defaults: {_format: json}

authors:
    resource: "@CypressTestBundle/Controller/AuthorsController.php"
    type:     rest
    prefix:   /api
    defaults: {_format: json}
