Cypress\TestBundle\Entity\Book:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [ books, authors ]
        title:
            expose: true
            groups: [ books, authors ]
        author:
            expose: true
            groups: [ books ]
        finiteState:
            expose: true
            groups: [ books, authors ]